### ISSUE TITLE
NoMethodError: undefined method `positive?' for 6:Fixnum

### ISSUE THREAD

**Issue by nitinkhairnar** [mtking2/img2zpl#6]
Getting this error on below line bold line.

img = Img2Zpl::Image.open("file.jpg")
**zpl = img.to_zpl**

Please check this urgently.

**Comment by mtking2** [comment]
What is your version of ruby?

**Comment by nitinkhairnar** [comment]
ruby 2.2.3p173

**Comment by mtking2** [comment]
Ah. @nitinkhairnar that version is very out of date at this point. The [end of life for ruby 2.2](https://www.ruby-lang.org/en/downloads/branches/) was March 2018.

[`positive?`](https://apidock.com/ruby/v2_4_6/Numeric/positive%3F) wasn't added until ruby 2.4.6. Even the [EOL for 2.4](https://www.ruby-lang.org/en/downloads/branches/) was last year (March 2020).

At a minimum I would recommend upgrading to ruby 2.5.
